### ISSUE TITLE
Deduplicate People from CSV preserves record with oldest `last_seen`

### ISSUE THREAD

**Issue by dylan-kinsa** [mixpanel/mixpanel_api#27] opened 2021-01-13 19:57 UTC
## Expected Behavior

Per this [docstring](https://github.com/mixpanel/mixpanel_api/blob/master/__init__.py#L629), it is expected that `deduplicate_people` will keep the most recently seen record when deduplication, and delete the others:

> Determines duplicate profiles based on the value of a specified property. _The profile with the latest
$last_seen is kept and the others are deleted_. Optionally adds any properties from the profiles to be deleted to
the remaining profile using $set_once. Backup files are always created.

## Actual Behavior

The opposite behavior occurs, i.e. the record with the _oldest_ `$last_seen` is preserved, the most recent is deleted. Using the following CSV data:
```
$distinct_id,$properties.$name,$properties.$email,$properties.$last_seen
id-2,undefined,undefined,2021-01-13T04:28:48
id-1,undefined,undefined,2021-01-13T04:28:34
```
Note that the line item with `$distinct_id`: `id-2` should have been preserved, but it's properties were merged into `id-1` and deleted.

**Comment by dylan-kinsa** [comment] 2021-01-13 20:10
After more tests, when using a CSV as the input, it looks like it treats the first record as the duplicate to be removed. So in this configuration, `id-2` would have been kept:
```
$distinct_id,$properties.$name,$properties.$email,$properties.$last_seen
id-1,undefined,undefined,2021-01-13T04:28:34
id-2,undefined,undefined,2021-01-13T04:28:48
```
This should probably be documented for the `profiles` param

**Comment by jaredmixpanel** [comment] 2021-02-18 21:40
@dylan-kinsa I was not able to reproduce this behavior. I believe you were able to work through this issue with my colleague Sam on the support team, so I'm going to go ahead and close this, but feel free to re-open with a more detailed description of how exactly to reproduce if you continue to experience this problem.

**Closed by jaredmixpanel** 2021-02-18 21:40 UTC
